name: Handson Env Variables
on: workflow_dispatch
jobs:
  Execute-Python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: running Python Script
        run: python python/cicd/sample.py
        env:
          USER_NAME: ${{ secrets.SecretUserName }} 
          PASSWORD: ${{ secrets.SecretPassword }} 